import PropTypes from "prop-types";
import styles from "./Hero.module.css";

const Hero = ({ className = "" }) => {
  return (
    <section className={[styles.aboutUsContentWrapper, className].join(" ")}>
      <div className={styles.aboutUsContent}>
        <div className={styles.aboutUsInnerContent}>
          <div className={styles.aboutUsNestedContent}>
            <div className={styles.aboutUsNestedContentInner}>
              <div className={styles.aboutUsParent}>
                <div className={styles.aboutUs}>About us</div>
                <div className={styles.aboutUsDescription}>
                  <h1 className={styles.whoWeAreContainer}>
                    <p className={styles.whoWeAre}>{`Who we are `}</p>
                    <p className={styles.andWhatWe}>and what we do</p>
                  </h1>
                  <div className={styles.loremIpsumDolor}>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                    Purus quis eget viverra integer aliquam enim volutpat nisi,
                    in.
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className={styles.frameParent}>
          <div className={styles.frameGroup}>
            <div className={styles.ellipseParent}>
              <div className={styles.frameChild} />
              <div className={styles.frameItem} />
              <div className={styles.frameInner} />
              <div className={styles.ellipseDiv} />
              <div className={styles.frameChild1} />
              <div className={styles.frameChild2} />
              <div className={styles.frameChild3} />
              <div className={styles.frameChild4} />
              <div className={styles.frameChild5} />
              <div className={styles.frameChild6} />
              <div className={styles.frameChild7} />
              <div className={styles.frameChild8} />
              <div className={styles.frameChild9} />
              <div className={styles.frameChild10} />
              <div className={styles.frameChild11} />
              <div className={styles.frameChild12} />
              <div className={styles.frameChild13} />
              <div className={styles.frameChild14} />
            </div>
            <div className={styles.ellipseGroup}>
              <div className={styles.frameChild15} />
              <div className={styles.frameChild16} />
              <div className={styles.frameChild17} />
              <div className={styles.frameChild18} />
              <div className={styles.frameChild19} />
              <div className={styles.frameChild20} />
              <div className={styles.frameChild21} />
              <div className={styles.frameChild22} />
              <div className={styles.frameChild23} />
              <div className={styles.frameChild24} />
              <div className={styles.frameChild25} />
              <div className={styles.frameChild26} />
              <div className={styles.frameChild27} />
              <div className={styles.frameChild28} />
              <div className={styles.frameChild29} />
              <div className={styles.frameChild30} />
              <div className={styles.frameChild31} />
              <div className={styles.frameChild32} />
            </div>
            <div className={styles.ellipseContainer}>
              <div className={styles.frameChild33} />
              <div className={styles.frameChild34} />
              <div className={styles.frameChild35} />
              <div className={styles.frameChild36} />
              <div className={styles.frameChild37} />
              <div className={styles.frameChild38} />
              <div className={styles.frameChild39} />
              <div className={styles.frameChild40} />
              <div className={styles.frameChild41} />
              <div className={styles.frameChild42} />
              <div className={styles.frameChild43} />
              <div className={styles.frameChild44} />
              <div className={styles.frameChild45} />
              <div className={styles.frameChild46} />
              <div className={styles.frameChild47} />
              <div className={styles.frameChild48} />
              <div className={styles.frameChild49} />
              <div className={styles.frameChild50} />
            </div>
            <div className={styles.frameDiv}>
              <div className={styles.frameChild51} />
              <div className={styles.frameChild52} />
              <div className={styles.frameChild53} />
              <div className={styles.frameChild54} />
              <div className={styles.frameChild55} />
              <div className={styles.frameChild56} />
              <div className={styles.frameChild57} />
              <div className={styles.frameChild58} />
              <div className={styles.frameChild59} />
              <div className={styles.frameChild60} />
              <div className={styles.frameChild61} />
              <div className={styles.frameChild62} />
              <div className={styles.frameChild63} />
              <div className={styles.frameChild64} />
              <div className={styles.frameChild65} />
              <div className={styles.frameChild66} />
              <div className={styles.frameChild67} />
              <div className={styles.frameChild68} />
            </div>
            <div className={styles.ellipseParent1}>
              <div className={styles.frameChild69} />
              <div className={styles.frameChild70} />
              <div className={styles.frameChild71} />
              <div className={styles.frameChild72} />
              <div className={styles.frameChild73} />
              <div className={styles.frameChild74} />
              <div className={styles.frameChild75} />
              <div className={styles.frameChild76} />
              <div className={styles.frameChild77} />
              <div className={styles.frameChild78} />
              <div className={styles.frameChild79} />
              <div className={styles.frameChild80} />
              <div className={styles.frameChild81} />
              <div className={styles.frameChild82} />
              <div className={styles.frameChild83} />
              <div className={styles.frameChild84} />
              <div className={styles.frameChild85} />
              <div className={styles.frameChild86} />
            </div>
            <div className={styles.ellipseParent2}>
              <div className={styles.frameChild87} />
              <div className={styles.frameChild88} />
              <div className={styles.frameChild89} />
              <div className={styles.frameChild90} />
              <div className={styles.frameChild91} />
              <div className={styles.frameChild92} />
              <div className={styles.frameChild93} />
              <div className={styles.frameChild94} />
              <div className={styles.frameChild95} />
              <div className={styles.frameChild96} />
              <div className={styles.frameChild97} />
              <div className={styles.frameChild98} />
              <div className={styles.frameChild99} />
              <div className={styles.frameChild100} />
              <div className={styles.frameChild101} />
              <div className={styles.frameChild102} />
              <div className={styles.frameChild103} />
              <div className={styles.frameChild104} />
            </div>
            <div className={styles.ellipseParent3}>
              <div className={styles.frameChild105} />
              <div className={styles.frameChild106} />
              <div className={styles.frameChild107} />
              <div className={styles.frameChild108} />
              <div className={styles.frameChild109} />
              <div className={styles.frameChild110} />
              <div className={styles.frameChild111} />
              <div className={styles.frameChild112} />
              <div className={styles.frameChild113} />
              <div className={styles.frameChild114} />
              <div className={styles.frameChild115} />
              <div className={styles.frameChild116} />
              <div className={styles.frameChild117} />
              <div className={styles.frameChild118} />
              <div className={styles.frameChild119} />
              <div className={styles.frameChild120} />
              <div className={styles.frameChild121} />
              <div className={styles.frameChild122} />
            </div>
            <div className={styles.ellipseParent4}>
              <div className={styles.frameChild123} />
              <div className={styles.frameChild124} />
              <div className={styles.frameChild125} />
              <div className={styles.frameChild126} />
              <div className={styles.frameChild127} />
              <div className={styles.frameChild128} />
              <div className={styles.frameChild129} />
              <div className={styles.frameChild130} />
              <div className={styles.frameChild131} />
              <div className={styles.frameChild132} />
              <div className={styles.frameChild133} />
              <div className={styles.frameChild134} />
              <div className={styles.frameChild135} />
              <div className={styles.frameChild136} />
              <div className={styles.frameChild137} />
              <div className={styles.frameChild138} />
              <div className={styles.frameChild139} />
              <div className={styles.frameChild140} />
            </div>
            <div className={styles.ellipseParent5}>
              <div className={styles.frameChild141} />
              <div className={styles.frameChild142} />
              <div className={styles.frameChild143} />
              <div className={styles.frameChild144} />
              <div className={styles.frameChild145} />
              <div className={styles.frameChild146} />
              <div className={styles.frameChild147} />
              <div className={styles.frameChild148} />
              <div className={styles.frameChild149} />
              <div className={styles.frameChild150} />
              <div className={styles.frameChild151} />
              <div className={styles.frameChild152} />
              <div className={styles.frameChild153} />
              <div className={styles.frameChild154} />
              <div className={styles.frameChild155} />
              <div className={styles.frameChild156} />
              <div className={styles.frameChild157} />
              <div className={styles.frameChild158} />
            </div>
            <div className={styles.ellipseParent6}>
              <div className={styles.frameChild159} />
              <div className={styles.frameChild160} />
              <div className={styles.frameChild161} />
              <div className={styles.frameChild162} />
              <div className={styles.frameChild163} />
              <div className={styles.frameChild164} />
              <div className={styles.frameChild165} />
              <div className={styles.frameChild166} />
              <div className={styles.frameChild167} />
              <div className={styles.frameChild168} />
              <div className={styles.frameChild169} />
              <div className={styles.frameChild170} />
              <div className={styles.frameChild171} />
              <div className={styles.frameChild172} />
              <div className={styles.frameChild173} />
              <div className={styles.frameChild174} />
              <div className={styles.frameChild175} />
              <div className={styles.frameChild176} />
            </div>
            <div className={styles.ellipseParent7}>
              <div className={styles.frameChild177} />
              <div className={styles.frameChild178} />
              <div className={styles.frameChild179} />
              <div className={styles.frameChild180} />
              <div className={styles.frameChild181} />
              <div className={styles.frameChild182} />
              <div className={styles.frameChild183} />
              <div className={styles.frameChild184} />
              <div className={styles.frameChild185} />
              <div className={styles.frameChild186} />
              <div className={styles.frameChild187} />
              <div className={styles.frameChild188} />
              <div className={styles.frameChild189} />
              <div className={styles.frameChild190} />
              <div className={styles.frameChild191} />
              <div className={styles.frameChild192} />
              <div className={styles.frameChild193} />
              <div className={styles.frameChild194} />
            </div>
            <div className={styles.ellipseParent8}>
              <div className={styles.frameChild195} />
              <div className={styles.frameChild196} />
              <div className={styles.frameChild197} />
              <div className={styles.frameChild198} />
              <div className={styles.frameChild199} />
              <div className={styles.frameChild200} />
              <div className={styles.frameChild201} />
              <div className={styles.frameChild202} />
              <div className={styles.frameChild203} />
              <div className={styles.frameChild204} />
              <div className={styles.frameChild205} />
              <div className={styles.frameChild206} />
              <div className={styles.frameChild207} />
              <div className={styles.frameChild208} />
              <div className={styles.frameChild209} />
              <div className={styles.frameChild210} />
              <div className={styles.frameChild211} />
              <div className={styles.frameChild212} />
            </div>
            <div className={styles.ellipseParent9}>
              <div className={styles.frameChild213} />
              <div className={styles.frameChild214} />
              <div className={styles.frameChild215} />
              <div className={styles.frameChild216} />
              <div className={styles.frameChild217} />
              <div className={styles.frameChild218} />
              <div className={styles.frameChild219} />
              <div className={styles.frameChild220} />
              <div className={styles.frameChild221} />
              <div className={styles.frameChild222} />
              <div className={styles.frameChild223} />
              <div className={styles.frameChild224} />
              <div className={styles.frameChild225} />
              <div className={styles.frameChild226} />
              <div className={styles.frameChild227} />
              <div className={styles.frameChild228} />
              <div className={styles.frameChild229} />
              <div className={styles.frameChild230} />
            </div>
            <div className={styles.ellipseParent10}>
              <div className={styles.frameChild231} />
              <div className={styles.frameChild232} />
              <div className={styles.frameChild233} />
              <div className={styles.frameChild234} />
              <div className={styles.frameChild235} />
              <div className={styles.frameChild236} />
              <div className={styles.frameChild237} />
              <div className={styles.frameChild238} />
              <div className={styles.frameChild239} />
              <div className={styles.frameChild240} />
              <div className={styles.frameChild241} />
              <div className={styles.frameChild242} />
              <div className={styles.frameChild243} />
              <div className={styles.frameChild244} />
              <div className={styles.frameChild245} />
              <div className={styles.frameChild246} />
              <div className={styles.frameChild247} />
              <div className={styles.frameChild248} />
            </div>
            <div className={styles.ellipseParent11}>
              <div className={styles.frameChild249} />
              <div className={styles.frameChild250} />
              <div className={styles.frameChild251} />
              <div className={styles.frameChild252} />
              <div className={styles.frameChild253} />
              <div className={styles.frameChild254} />
              <div className={styles.frameChild255} />
              <div className={styles.frameChild256} />
              <div className={styles.frameChild257} />
              <div className={styles.frameChild258} />
              <div className={styles.frameChild259} />
              <div className={styles.frameChild260} />
              <div className={styles.frameChild261} />
              <div className={styles.frameChild262} />
              <div className={styles.frameChild263} />
              <div className={styles.frameChild264} />
              <div className={styles.frameChild265} />
              <div className={styles.frameChild266} />
            </div>
            <div className={styles.ellipseParent12}>
              <div className={styles.frameChild267} />
              <div className={styles.frameChild268} />
              <div className={styles.frameChild269} />
              <div className={styles.frameChild270} />
              <div className={styles.frameChild271} />
              <div className={styles.frameChild272} />
              <div className={styles.frameChild273} />
              <div className={styles.frameChild274} />
              <div className={styles.frameChild275} />
              <div className={styles.frameChild276} />
              <div className={styles.frameChild277} />
              <div className={styles.frameChild278} />
              <div className={styles.frameChild279} />
              <div className={styles.frameChild280} />
              <div className={styles.frameChild281} />
              <div className={styles.frameChild282} />
              <div className={styles.frameChild283} />
              <div className={styles.frameChild284} />
            </div>
            <div className={styles.ellipseParent13}>
              <div className={styles.frameChild285} />
              <div className={styles.frameChild286} />
              <div className={styles.frameChild287} />
              <div className={styles.frameChild288} />
              <div className={styles.frameChild289} />
              <div className={styles.frameChild290} />
              <div className={styles.frameChild291} />
              <div className={styles.frameChild292} />
              <div className={styles.frameChild293} />
              <div className={styles.frameChild294} />
              <div className={styles.frameChild295} />
              <div className={styles.frameChild296} />
              <div className={styles.frameChild297} />
              <div className={styles.frameChild298} />
              <div className={styles.frameChild299} />
              <div className={styles.frameChild300} />
              <div className={styles.frameChild301} />
              <div className={styles.frameChild302} />
            </div>
            <div className={styles.ellipseParent14}>
              <div className={styles.frameChild303} />
              <div className={styles.frameChild304} />
              <div className={styles.frameChild305} />
              <div className={styles.frameChild306} />
              <div className={styles.frameChild307} />
              <div className={styles.frameChild308} />
              <div className={styles.frameChild309} />
              <div className={styles.frameChild310} />
              <div className={styles.frameChild311} />
              <div className={styles.frameChild312} />
              <div className={styles.frameChild313} />
              <div className={styles.frameChild314} />
              <div className={styles.frameChild315} />
              <div className={styles.frameChild316} />
              <div className={styles.frameChild317} />
              <div className={styles.frameChild318} />
              <div className={styles.frameChild319} />
              <div className={styles.frameChild320} />
            </div>
            <div className={styles.ellipseParent15}>
              <div className={styles.frameChild321} />
              <div className={styles.frameChild322} />
              <div className={styles.frameChild323} />
              <div className={styles.frameChild324} />
              <div className={styles.frameChild325} />
              <div className={styles.frameChild326} />
              <div className={styles.frameChild327} />
              <div className={styles.frameChild328} />
              <div className={styles.frameChild329} />
              <div className={styles.frameChild330} />
              <div className={styles.frameChild331} />
              <div className={styles.frameChild332} />
              <div className={styles.frameChild333} />
              <div className={styles.frameChild334} />
              <div className={styles.frameChild335} />
              <div className={styles.frameChild336} />
              <div className={styles.frameChild337} />
              <div className={styles.frameChild338} />
            </div>
            <div className={styles.ellipseParent16}>
              <div className={styles.frameChild339} />
              <div className={styles.frameChild340} />
              <div className={styles.frameChild341} />
              <div className={styles.frameChild342} />
              <div className={styles.frameChild343} />
              <div className={styles.frameChild344} />
              <div className={styles.frameChild345} />
              <div className={styles.frameChild346} />
              <div className={styles.frameChild347} />
              <div className={styles.frameChild348} />
              <div className={styles.frameChild349} />
              <div className={styles.frameChild350} />
              <div className={styles.frameChild351} />
              <div className={styles.frameChild352} />
              <div className={styles.frameChild353} />
              <div className={styles.frameChild354} />
              <div className={styles.frameChild355} />
              <div className={styles.frameChild356} />
            </div>
            <div className={styles.ellipseParent17}>
              <div className={styles.frameChild357} />
              <div className={styles.frameChild358} />
              <div className={styles.frameChild359} />
              <div className={styles.frameChild360} />
              <div className={styles.frameChild361} />
              <div className={styles.frameChild362} />
              <div className={styles.frameChild363} />
              <div className={styles.frameChild364} />
              <div className={styles.frameChild365} />
              <div className={styles.frameChild366} />
              <div className={styles.frameChild367} />
              <div className={styles.frameChild368} />
              <div className={styles.frameChild369} />
              <div className={styles.frameChild370} />
              <div className={styles.frameChild371} />
              <div className={styles.frameChild372} />
              <div className={styles.frameChild373} />
              <div className={styles.frameChild374} />
            </div>
            <div className={styles.ellipseParent18}>
              <div className={styles.frameChild375} />
              <div className={styles.frameChild376} />
              <div className={styles.frameChild377} />
              <div className={styles.frameChild378} />
              <div className={styles.frameChild379} />
              <div className={styles.frameChild380} />
              <div className={styles.frameChild381} />
              <div className={styles.frameChild382} />
              <div className={styles.frameChild383} />
              <div className={styles.frameChild384} />
              <div className={styles.frameChild385} />
              <div className={styles.frameChild386} />
              <div className={styles.frameChild387} />
              <div className={styles.frameChild388} />
              <div className={styles.frameChild389} />
              <div className={styles.frameChild390} />
              <div className={styles.frameChild391} />
              <div className={styles.frameChild392} />
            </div>
            <div className={styles.ellipseParent19}>
              <div className={styles.frameChild393} />
              <div className={styles.frameChild394} />
              <div className={styles.frameChild395} />
              <div className={styles.frameChild396} />
              <div className={styles.frameChild397} />
              <div className={styles.frameChild398} />
              <div className={styles.frameChild399} />
              <div className={styles.frameChild400} />
              <div className={styles.frameChild401} />
              <div className={styles.frameChild402} />
              <div className={styles.frameChild403} />
              <div className={styles.frameChild404} />
              <div className={styles.frameChild405} />
              <div className={styles.frameChild406} />
              <div className={styles.frameChild407} />
              <div className={styles.frameChild408} />
              <div className={styles.frameChild409} />
              <div className={styles.frameChild410} />
            </div>
            <div className={styles.ellipseParent20}>
              <div className={styles.frameChild411} />
              <div className={styles.frameChild412} />
              <div className={styles.frameChild413} />
              <div className={styles.frameChild414} />
              <div className={styles.frameChild415} />
              <div className={styles.frameChild416} />
              <div className={styles.frameChild417} />
              <div className={styles.frameChild418} />
              <div className={styles.frameChild419} />
              <div className={styles.frameChild420} />
              <div className={styles.frameChild421} />
              <div className={styles.frameChild422} />
              <div className={styles.frameChild423} />
              <div className={styles.frameChild424} />
              <div className={styles.frameChild425} />
              <div className={styles.frameChild426} />
              <div className={styles.frameChild427} />
              <div className={styles.frameChild428} />
            </div>
            <div className={styles.ellipseParent21}>
              <div className={styles.frameChild429} />
              <div className={styles.frameChild430} />
              <div className={styles.frameChild431} />
              <div className={styles.frameChild432} />
              <div className={styles.frameChild433} />
              <div className={styles.frameChild434} />
              <div className={styles.frameChild435} />
              <div className={styles.frameChild436} />
              <div className={styles.frameChild437} />
              <div className={styles.frameChild438} />
              <div className={styles.frameChild439} />
              <div className={styles.frameChild440} />
              <div className={styles.frameChild441} />
              <div className={styles.frameChild442} />
              <div className={styles.frameChild443} />
              <div className={styles.frameChild444} />
              <div className={styles.frameChild445} />
              <div className={styles.frameChild446} />
            </div>
            <div className={styles.ellipseParent22}>
              <div className={styles.frameChild447} />
              <div className={styles.frameChild448} />
              <div className={styles.frameChild449} />
              <div className={styles.frameChild450} />
              <div className={styles.frameChild451} />
              <div className={styles.frameChild452} />
              <div className={styles.frameChild453} />
              <div className={styles.frameChild454} />
              <div className={styles.frameChild455} />
              <div className={styles.frameChild456} />
              <div className={styles.frameChild457} />
              <div className={styles.frameChild458} />
              <div className={styles.frameChild459} />
              <div className={styles.frameChild460} />
              <div className={styles.frameChild461} />
              <div className={styles.frameChild462} />
              <div className={styles.frameChild463} />
              <div className={styles.frameChild464} />
            </div>
            <div className={styles.ellipseParent23}>
              <div className={styles.frameChild465} />
              <div className={styles.frameChild466} />
              <div className={styles.frameChild467} />
              <div className={styles.frameChild468} />
              <div className={styles.frameChild469} />
              <div className={styles.frameChild470} />
              <div className={styles.frameChild471} />
              <div className={styles.frameChild472} />
              <div className={styles.frameChild473} />
              <div className={styles.frameChild474} />
              <div className={styles.frameChild475} />
              <div className={styles.frameChild476} />
              <div className={styles.frameChild477} />
              <div className={styles.frameChild478} />
              <div className={styles.frameChild479} />
              <div className={styles.frameChild480} />
              <div className={styles.frameChild481} />
              <div className={styles.frameChild482} />
            </div>
            <div className={styles.ellipseParent24}>
              <div className={styles.frameChild483} />
              <div className={styles.frameChild484} />
              <div className={styles.frameChild485} />
              <div className={styles.frameChild486} />
              <div className={styles.frameChild487} />
              <div className={styles.frameChild488} />
              <div className={styles.frameChild489} />
              <div className={styles.frameChild490} />
              <div className={styles.frameChild491} />
              <div className={styles.frameChild492} />
              <div className={styles.frameChild493} />
              <div className={styles.frameChild494} />
              <div className={styles.frameChild495} />
              <div className={styles.frameChild496} />
              <div className={styles.frameChild497} />
              <div className={styles.frameChild498} />
              <div className={styles.frameChild499} />
              <div className={styles.frameChild500} />
            </div>
            <div className={styles.ellipseParent25}>
              <div className={styles.frameChild501} />
              <div className={styles.frameChild502} />
              <div className={styles.frameChild503} />
              <div className={styles.frameChild504} />
              <div className={styles.frameChild505} />
              <div className={styles.frameChild506} />
              <div className={styles.frameChild507} />
              <div className={styles.frameChild508} />
              <div className={styles.frameChild509} />
              <div className={styles.frameChild510} />
              <div className={styles.frameChild511} />
              <div className={styles.frameChild512} />
              <div className={styles.frameChild513} />
              <div className={styles.frameChild514} />
              <div className={styles.frameChild515} />
              <div className={styles.frameChild516} />
              <div className={styles.frameChild517} />
              <div className={styles.frameChild518} />
            </div>
            <div className={styles.ellipseParent26}>
              <div className={styles.frameChild519} />
              <div className={styles.frameChild520} />
              <div className={styles.frameChild521} />
              <div className={styles.frameChild522} />
              <div className={styles.frameChild523} />
              <div className={styles.frameChild524} />
              <div className={styles.frameChild525} />
              <div className={styles.frameChild526} />
              <div className={styles.frameChild527} />
              <div className={styles.frameChild528} />
              <div className={styles.frameChild529} />
              <div className={styles.frameChild530} />
              <div className={styles.frameChild531} />
              <div className={styles.frameChild532} />
              <div className={styles.frameChild533} />
              <div className={styles.frameChild534} />
              <div className={styles.frameChild535} />
              <div className={styles.frameChild536} />
            </div>
            <div className={styles.ellipseParent27}>
              <div className={styles.frameChild537} />
              <div className={styles.frameChild538} />
              <div className={styles.frameChild539} />
              <div className={styles.frameChild540} />
              <div className={styles.frameChild541} />
              <div className={styles.frameChild542} />
              <div className={styles.frameChild543} />
              <div className={styles.frameChild544} />
              <div className={styles.frameChild545} />
              <div className={styles.frameChild546} />
              <div className={styles.frameChild547} />
              <div className={styles.frameChild548} />
              <div className={styles.frameChild549} />
              <div className={styles.frameChild550} />
              <div className={styles.frameChild551} />
              <div className={styles.frameChild552} />
              <div className={styles.frameChild553} />
              <div className={styles.frameChild554} />
            </div>
            <div className={styles.ellipseParent28}>
              <div className={styles.frameChild555} />
              <div className={styles.frameChild556} />
              <div className={styles.frameChild557} />
              <div className={styles.frameChild558} />
              <div className={styles.frameChild559} />
              <div className={styles.frameChild560} />
              <div className={styles.frameChild561} />
              <div className={styles.frameChild562} />
              <div className={styles.frameChild563} />
              <div className={styles.frameChild564} />
              <div className={styles.frameChild565} />
              <div className={styles.frameChild566} />
              <div className={styles.frameChild567} />
              <div className={styles.frameChild568} />
              <div className={styles.frameChild569} />
              <div className={styles.frameChild570} />
              <div className={styles.frameChild571} />
              <div className={styles.frameChild572} />
            </div>
            <div className={styles.ellipseParent29}>
              <div className={styles.frameChild573} />
              <div className={styles.frameChild574} />
              <div className={styles.frameChild575} />
              <div className={styles.frameChild576} />
              <div className={styles.frameChild577} />
              <div className={styles.frameChild578} />
              <div className={styles.frameChild579} />
              <div className={styles.frameChild580} />
              <div className={styles.frameChild581} />
              <div className={styles.frameChild582} />
              <div className={styles.frameChild583} />
              <div className={styles.frameChild584} />
              <div className={styles.frameChild585} />
              <div className={styles.frameChild586} />
              <div className={styles.frameChild587} />
              <div className={styles.frameChild588} />
              <div className={styles.frameChild589} />
              <div className={styles.frameChild590} />
            </div>
            <div className={styles.ellipseParent30}>
              <div className={styles.frameChild591} />
              <div className={styles.frameChild592} />
              <div className={styles.frameChild593} />
              <div className={styles.frameChild594} />
              <div className={styles.frameChild595} />
              <div className={styles.frameChild596} />
              <div className={styles.frameChild597} />
              <div className={styles.frameChild598} />
              <div className={styles.frameChild599} />
              <div className={styles.frameChild600} />
              <div className={styles.frameChild601} />
              <div className={styles.frameChild602} />
              <div className={styles.frameChild603} />
              <div className={styles.frameChild604} />
              <div className={styles.frameChild605} />
              <div className={styles.frameChild606} />
              <div className={styles.frameChild607} />
              <div className={styles.frameChild608} />
            </div>
            <div className={styles.ellipseParent31}>
              <div className={styles.frameChild609} />
              <div className={styles.frameChild610} />
              <div className={styles.frameChild611} />
              <div className={styles.frameChild612} />
              <div className={styles.frameChild613} />
              <div className={styles.frameChild614} />
              <div className={styles.frameChild615} />
              <div className={styles.frameChild616} />
              <div className={styles.frameChild617} />
              <div className={styles.frameChild618} />
              <div className={styles.frameChild619} />
              <div className={styles.frameChild620} />
              <div className={styles.frameChild621} />
              <div className={styles.frameChild622} />
              <div className={styles.frameChild623} />
              <div className={styles.frameChild624} />
              <div className={styles.frameChild625} />
              <div className={styles.frameChild626} />
            </div>
            <div className={styles.ellipseParent32}>
              <div className={styles.frameChild627} />
              <div className={styles.frameChild628} />
              <div className={styles.frameChild629} />
              <div className={styles.frameChild630} />
              <div className={styles.frameChild631} />
              <div className={styles.frameChild632} />
              <div className={styles.frameChild633} />
              <div className={styles.frameChild634} />
              <div className={styles.frameChild635} />
              <div className={styles.frameChild636} />
              <div className={styles.frameChild637} />
              <div className={styles.frameChild638} />
              <div className={styles.frameChild639} />
              <div className={styles.frameChild640} />
              <div className={styles.frameChild641} />
              <div className={styles.frameChild642} />
              <div className={styles.frameChild643} />
              <div className={styles.frameChild644} />
            </div>
            <div className={styles.ellipseParent33}>
              <div className={styles.frameChild645} />
              <div className={styles.frameChild646} />
              <div className={styles.frameChild647} />
              <div className={styles.frameChild648} />
              <div className={styles.frameChild649} />
              <div className={styles.frameChild650} />
              <div className={styles.frameChild651} />
              <div className={styles.frameChild652} />
              <div className={styles.frameChild653} />
              <div className={styles.frameChild654} />
              <div className={styles.frameChild655} />
              <div className={styles.frameChild656} />
              <div className={styles.frameChild657} />
              <div className={styles.frameChild658} />
              <div className={styles.frameChild659} />
              <div className={styles.frameChild660} />
              <div className={styles.frameChild661} />
              <div className={styles.frameChild662} />
            </div>
            <div className={styles.ellipseParent34}>
              <div className={styles.frameChild663} />
              <div className={styles.frameChild664} />
              <div className={styles.frameChild665} />
              <div className={styles.frameChild666} />
              <div className={styles.frameChild667} />
              <div className={styles.frameChild668} />
              <div className={styles.frameChild669} />
              <div className={styles.frameChild670} />
              <div className={styles.frameChild671} />
              <div className={styles.frameChild672} />
              <div className={styles.frameChild673} />
              <div className={styles.frameChild674} />
              <div className={styles.frameChild675} />
              <div className={styles.frameChild676} />
              <div className={styles.frameChild677} />
              <div className={styles.frameChild678} />
              <div className={styles.frameChild679} />
              <div className={styles.frameChild680} />
            </div>
            <div className={styles.ellipseParent35}>
              <div className={styles.frameChild681} />
              <div className={styles.frameChild682} />
              <div className={styles.frameChild683} />
              <div className={styles.frameChild684} />
              <div className={styles.frameChild685} />
              <div className={styles.frameChild686} />
              <div className={styles.frameChild687} />
              <div className={styles.frameChild688} />
              <div className={styles.frameChild689} />
              <div className={styles.frameChild690} />
              <div className={styles.frameChild691} />
              <div className={styles.frameChild692} />
              <div className={styles.frameChild693} />
              <div className={styles.frameChild694} />
              <div className={styles.frameChild695} />
              <div className={styles.frameChild696} />
              <div className={styles.frameChild697} />
              <div className={styles.frameChild698} />
            </div>
            <div className={styles.ellipseParent36}>
              <div className={styles.frameChild699} />
              <div className={styles.frameChild700} />
              <div className={styles.frameChild701} />
              <div className={styles.frameChild702} />
              <div className={styles.frameChild703} />
              <div className={styles.frameChild704} />
              <div className={styles.frameChild705} />
              <div className={styles.frameChild706} />
              <div className={styles.frameChild707} />
              <div className={styles.frameChild708} />
              <div className={styles.frameChild709} />
              <div className={styles.frameChild710} />
              <div className={styles.frameChild711} />
              <div className={styles.frameChild712} />
              <div className={styles.frameChild713} />
              <div className={styles.frameChild714} />
              <div className={styles.frameChild715} />
              <div className={styles.frameChild716} />
            </div>
            <div className={styles.ellipseParent37}>
              <div className={styles.frameChild717} />
              <div className={styles.frameChild718} />
              <div className={styles.frameChild719} />
              <div className={styles.frameChild720} />
              <div className={styles.frameChild721} />
              <div className={styles.frameChild722} />
              <div className={styles.frameChild723} />
              <div className={styles.frameChild724} />
              <div className={styles.frameChild725} />
              <div className={styles.frameChild726} />
              <div className={styles.frameChild727} />
              <div className={styles.frameChild728} />
              <div className={styles.frameChild729} />
              <div className={styles.frameChild730} />
              <div className={styles.frameChild731} />
              <div className={styles.frameChild732} />
              <div className={styles.frameChild733} />
              <div className={styles.frameChild734} />
            </div>
            <div className={styles.ellipseParent38}>
              <div className={styles.frameChild735} />
              <div className={styles.frameChild736} />
              <div className={styles.frameChild737} />
              <div className={styles.frameChild738} />
              <div className={styles.frameChild739} />
              <div className={styles.frameChild740} />
              <div className={styles.frameChild741} />
              <div className={styles.frameChild742} />
              <div className={styles.frameChild743} />
              <div className={styles.frameChild744} />
              <div className={styles.frameChild745} />
              <div className={styles.frameChild746} />
              <div className={styles.frameChild747} />
              <div className={styles.frameChild748} />
              <div className={styles.frameChild749} />
              <div className={styles.frameChild750} />
              <div className={styles.frameChild751} />
              <div className={styles.frameChild752} />
            </div>
            <div className={styles.ellipseParent39}>
              <div className={styles.frameChild753} />
              <div className={styles.frameChild754} />
              <div className={styles.frameChild755} />
              <div className={styles.frameChild756} />
              <div className={styles.frameChild757} />
              <div className={styles.frameChild758} />
              <div className={styles.frameChild759} />
              <div className={styles.frameChild760} />
              <div className={styles.frameChild761} />
              <div className={styles.frameChild762} />
              <div className={styles.frameChild763} />
              <div className={styles.frameChild764} />
              <div className={styles.frameChild765} />
              <div className={styles.frameChild766} />
              <div className={styles.frameChild767} />
              <div className={styles.frameChild768} />
              <div className={styles.frameChild769} />
              <div className={styles.frameChild770} />
            </div>
            <div className={styles.ellipseParent40}>
              <div className={styles.frameChild771} />
              <div className={styles.frameChild772} />
              <div className={styles.frameChild773} />
              <div className={styles.frameChild774} />
              <div className={styles.frameChild775} />
              <div className={styles.frameChild776} />
              <div className={styles.frameChild777} />
              <div className={styles.frameChild778} />
              <div className={styles.frameChild779} />
              <div className={styles.frameChild780} />
              <div className={styles.frameChild781} />
              <div className={styles.frameChild782} />
              <div className={styles.frameChild783} />
              <div className={styles.frameChild784} />
              <div className={styles.frameChild785} />
              <div className={styles.frameChild786} />
              <div className={styles.frameChild787} />
              <div className={styles.frameChild788} />
            </div>
            <div className={styles.ellipseParent41}>
              <div className={styles.frameChild789} />
              <div className={styles.frameChild790} />
              <div className={styles.frameChild791} />
              <div className={styles.frameChild792} />
              <div className={styles.frameChild793} />
              <div className={styles.frameChild794} />
              <div className={styles.frameChild795} />
              <div className={styles.frameChild796} />
              <div className={styles.frameChild797} />
              <div className={styles.frameChild798} />
              <div className={styles.frameChild799} />
              <div className={styles.frameChild800} />
              <div className={styles.frameChild801} />
              <div className={styles.frameChild802} />
              <div className={styles.frameChild803} />
              <div className={styles.frameChild804} />
              <div className={styles.frameChild805} />
              <div className={styles.frameChild806} />
            </div>
            <div className={styles.ellipseParent42}>
              <div className={styles.frameChild807} />
              <div className={styles.frameChild808} />
              <div className={styles.frameChild809} />
              <div className={styles.frameChild810} />
              <div className={styles.frameChild811} />
              <div className={styles.frameChild812} />
              <div className={styles.frameChild813} />
              <div className={styles.frameChild814} />
              <div className={styles.frameChild815} />
              <div className={styles.frameChild816} />
              <div className={styles.frameChild817} />
              <div className={styles.frameChild818} />
              <div className={styles.frameChild819} />
              <div className={styles.frameChild820} />
              <div className={styles.frameChild821} />
              <div className={styles.frameChild822} />
              <div className={styles.frameChild823} />
              <div className={styles.frameChild824} />
            </div>
            <div className={styles.ellipseParent43}>
              <div className={styles.frameChild825} />
              <div className={styles.frameChild826} />
              <div className={styles.frameChild827} />
              <div className={styles.frameChild828} />
              <div className={styles.frameChild829} />
              <div className={styles.frameChild830} />
              <div className={styles.frameChild831} />
              <div className={styles.frameChild832} />
              <div className={styles.frameChild833} />
              <div className={styles.frameChild834} />
              <div className={styles.frameChild835} />
              <div className={styles.frameChild836} />
              <div className={styles.frameChild837} />
              <div className={styles.frameChild838} />
              <div className={styles.frameChild839} />
              <div className={styles.frameChild840} />
              <div className={styles.frameChild841} />
              <div className={styles.frameChild842} />
            </div>
            <div className={styles.ellipseParent44}>
              <div className={styles.frameChild843} />
              <div className={styles.frameChild844} />
              <div className={styles.frameChild845} />
              <div className={styles.frameChild846} />
              <div className={styles.frameChild847} />
              <div className={styles.frameChild848} />
              <div className={styles.frameChild849} />
              <div className={styles.frameChild850} />
              <div className={styles.frameChild851} />
              <div className={styles.frameChild852} />
              <div className={styles.frameChild853} />
              <div className={styles.frameChild854} />
              <div className={styles.frameChild855} />
              <div className={styles.frameChild856} />
              <div className={styles.frameChild857} />
              <div className={styles.frameChild858} />
              <div className={styles.frameChild859} />
              <div className={styles.frameChild860} />
            </div>
            <div className={styles.ellipseParent45}>
              <div className={styles.frameChild861} />
              <div className={styles.frameChild862} />
              <div className={styles.frameChild863} />
              <div className={styles.frameChild864} />
              <div className={styles.frameChild865} />
              <div className={styles.frameChild866} />
              <div className={styles.frameChild867} />
              <div className={styles.frameChild868} />
              <div className={styles.frameChild869} />
              <div className={styles.frameChild870} />
              <div className={styles.frameChild871} />
              <div className={styles.frameChild872} />
              <div className={styles.frameChild873} />
              <div className={styles.frameChild874} />
              <div className={styles.frameChild875} />
              <div className={styles.frameChild876} />
              <div className={styles.frameChild877} />
              <div className={styles.frameChild878} />
            </div>
          </div>
          <div className={styles.wrapperGroup55611577}>
            <img
              className={styles.wrapperGroup55611577Child}
              loading="lazy"
              alt=""
              src="/group-55611577.svg"
            />
          </div>
          <div className={styles.wrapperGroup55611578}>
            <img
              className={styles.wrapperGroup55611578Child}
              loading="lazy"
              alt=""
              src="/group-55611578.svg"
            />
          </div>
          <div className={styles.wrapperGroup55611579}>
            <img
              className={styles.wrapperGroup55611579Child}
              loading="lazy"
              alt=""
              src="/group-55611579.svg"
            />
          </div>
          <img
            className={styles.groupIcon}
            loading="lazy"
            alt=""
            src="/group-55611563@2x.png"
          />
        </div>
      </div>
    </section>
  );
};

Hero.propTypes = {
  className: PropTypes.string,
};

export default Hero;
